baseURL = "/"
languageCode = "en-us"
title = "KubePlatform"
theme = "kube"
description = "A production-ready Development Platform for Kubernetes"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "KubePlatform"
  github = "kube-platform"
  githubOrgPage = "https://github.com/kube-platform"
  email = "myemail@myaddress.xxx"

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "FAQ"
    weight = -100
    url = "/faq/"
