baseURL = "/"
languageCode = "en-us"
title = "KubePlatform"
theme = "kube-ng"
description = "A production-ready Development Platform for Kubernetes"
Paginate = 4
pygmentsUseClasses = true

[Params]
  RSSLink = "/index.xml"
  author = "KubePlatform"
  github = "kube-platform"
  githubOrgPage = "https://github.com/kube-platform"
  email = "myemail@myaddress.xxx"

[[menu.main]]
    name = "Home"
    weight = 100
    url = "/"
[[menu.main]]
    name = "Components"
    weight = 200
    url = "/components/"
[[menu.main]]
    name = "Architecture"
    weight = 300
    url = "/architecture/"
[[menu.main]]
    name = "Getting started"
    weight = 400
    url = "/getting-started/"
